apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: question-response-service
  name: question-response-service
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: question-response-service
  template:
    metadata:
      labels:
        app: question-response-service
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: apps2
                    operator: In
                    values:
                      - "true"
      imagePullSecrets:
        - name: gitlab-registry
      containers:
        - env:
            - name: MONGO_HOST 
              valueFrom:
                secretKeyRef:
                  name: mongo-secrets
                  key: mongo_host

            - name: MONGO_PORT
              valueFrom:
                secretKeyRef:
                  name: mongo-secrets
                  key: mongo_port

            - name: MONGO_DATABASE  
              valueFrom:
                secretKeyRef:
                  name: mongo-secrets
                  key: question_response_db

            - name: MONGO_PASSWORD  
              valueFrom:
                secretKeyRef:
                  name: mongo-secrets
                  key: question_response_pass

            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-secrets
                  key: question_response_user

            - name: MINIO_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: minio-secrets
                  key: minio_endpoint

            - name: MINIO_PORT
              valueFrom:
                secretKeyRef:
                  name: minio-secrets
                  key: minio_port

            - name: MINIO_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: minio-secrets
                  key: minio_access_key

            - name: MINIO_SECRET_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: minio-secrets
                  key: minio_secret_key

            - name: QUESTIONARY_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: services
                  key: QUESTIONARY_SERVICE_URL

            - name: USER_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: services
                  key: USER_SERVICE

            - name: USER_SERVICE_PORT
              value: "80"

            - name: QUESTONARY_SERVICE_GRPC_HOST
              value: "questionary-service"

            - name: QUESTONARY_SERVICE_GRPC_PORT
              value: "8080"

            - name: SPSS_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: services
                  key: SPSS_SERVICE_URL

            - name: KAFKA_HOST
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: kafka_host

            - name: KAFKA_PORT
              value: "9092"

            - name: HTTP_PORT
              value: "80"

            - name: GRPC_SERVER_PORT
              value: "8080"

            - name: LOG_LEVEL
              value: "debug"

            - name: TIME_ZONE
              value: "Z-Zulu"

            - name: NODE_ENV
              value: "prod"
          image: gitlab.udevs.io:5050/oxbox/ox_question_response_service:latest
          name: question-response-service
          imagePullPolicy: Always
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: question-response-service
  namespace: microservices
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: rpc
      port: 8080
      targetPort: 8080
  selector:
    app: question-response-service
